### ISSUE TITLE
Is there a way I can run and deploy using serverless commands ?

### ISSUE THREAD

**Issue by ddbhagat** [awslabs/aws-lambda-web-adapter#368]
Is there a way I can run and deploy using serverless commands ?
- npx sls offline start --stage local
- and npx sls deploy --stage

When I try to run this locally using above commands, getting below error

`
 Runtime.ImportModuleError: Error: Cannot find module 'run'
  Require stack:
  - /nextjs-zip/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js
      at _loadUserApp (/nextjs-zip/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js:310:15)
      at async module.exports.load (/nextjs-zip/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js:341:21)
      at async InProcessRunner.run (file:///nextjs-zip/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:41:21)
      at async MessagePort.<anonymous> (file:///nextjs-zip/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)
✖ Error: Cannot find module 'run'
  Require stack:
  - /nextjs-zip/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js
`

**Comment by bnusunny** [comment]
You can use 'sls' to deploy docker packaged lambda functions at this moment. For zip packaged lambda functions, I need to look deeper.

**Comment by ddbhagat** [comment]
Yes @bnusunny I have tried the docker version of it. It is working as expected. Looking forward for updates on zip deployment. Thanks !!

**Comment by qutek** [comment]
I have added an example implementation for those who are seeking an example of deploying a NestJs framework using the serverless framework

I made a PR here: https://github.com/awslabs/aws-lambda-web-adapter/pull/394
