### ISSUE TITLE
URLs that use `+` for encoding spaces in the query string case a panic

### ISSUE THREAD

**Issue by mkdynamic** [awslabs/aws-lambda-web-adapter#491]
When requesting a URL that encodes spaces in the query string using `+` instead of `%20`, for example:

GET /foo?q=a+b

```
2024-06-30T13:53:02.866 START RequestId: 5638602c-5ae7-42e2-b7b2-f22ae4b6b2d8 Version: 19
2024-06-30T13:53:02.866 thread 'main' panicked at 'failed to build request: http::Error(InvalidUri(InvalidUriChar))', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_http-0.8.3/src/request.rs:154:10
2024-06-30T13:53:02.866 ERROR Lambda runtime invoke{requestId="5638602c-5ae7-42e2-b7b2-f22ae4b6b2d8" xrayTraceId="Root=1-6681c5ae-494bc508401b34ae24c6a570;Parent=756e0c092b343606;Sampled=0;Lineage=681883e6:0"}: lambda_runtime: Any { .. }
2024-06-30T13:53:02.867 END RequestId: 5638602c-5ae7-42e2-b7b2-f22ae4b6b2d8
2024-06-30T13:53:02.867 REPORT RequestId: 5638602c-5ae7-42e2-b7b2-f22ae4b6b2d8	Duration: 1.43 ms	Billed Duration: 2 ms	Memory Size: 1769 MB	Max Memory Used: 624 MB
```

Whereas this works fine:

GET /foo?q=a%20b

This is in the context of calling a Lambda Function URL (via CloudFront).

Because encoding spaces this way is common and valid, I beleive it is not possible to fix this solely in the application layer (for example, we found the OAuth 2 callback URL form Google to use + to encode spaces in the scopes parameter, and we have no control over their encoding scheme).

Any clues?

**Comment by bnusunny** [comment]
What's the version of Lambda Web Adapter you used? I couldn't reproduce this error with the latest version of LWA.

**Comment by mkdynamic** [comment]
0.8.3

**Comment by mkdynamic** [comment]
Looking at the lambda-http version in that exception I notice it says 0.8.3 which correlates with LWA 0.7.2.

Let me confirm the version of LWA. It seems like I may be mistaken and am actually using an older version.

Apologies for not checking that first. Will re-open if I confirm the latest version.

**Comment by mkdynamic** [comment]
Confirmed this is still an issue with LWA 0.8.4:

```
START RequestId: 276bdf6d-8848-4501-a857-711f64ee675c Version: 111
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lambda_http-0.9.3/src/request.rs:161:10:
failed to build request: http::Error(InvalidUri(InvalidUriChar))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
08:36:59 system  | SIGTERM received, starting shutdown
RequestId: 276bdf6d-8848-4501-a857-711f64ee675c Error: signal: aborted
Extension.Crash
END RequestId: 276bdf6d-8848-4501-a857-711f64ee675c
REPORT RequestId: 276bdf6d-8848-4501-a857-711f64ee675c	Duration: 606.63 ms	Billed Duration: 607 ms	Memory Size: 1769 MB	Max Memory Used: 474 MB	
```

**Comment by bnusunny** [comment]
How did you invoke this function? Is it via API Gateway Rest API, HTTP API, ALB, or Function URL? 

I did a test with API Gateway Rest API, it does not trigger this error. You can try it here: 

https://httpbin-rest-zip.beta.adapter.awsguru.dev/get?q=a+b

**Comment by mkdynamic** [comment]
Lambda Function URL

**Comment by mkdynamic** [comment]
@bnusunny Are you able to repro when calling that Function URL directly (not via API Gateway)? If not, I will try and see if I can repro on a fresh Lambda function and figure out what configuration seems to be involved.

**Comment by bnusunny** [comment]
@mkdynamic No. I could not reproduce it with Function URL. It could be something else in the request caused that. If you could provide the full request payload, I could look deeper.

**Comment by mkdynamic** [comment]
Roger.

The request is simply a GET to /up?q=a+b with nothing else unusual. I am able to repro in 2 different apps both with different containers. Both using LWA via a Dockerfile.

Only other detail that I can thing of which may be relevant is that this is a Function URL on a Lambda Alias (not the lambda function). Seems unlikely but I wonder if that has different behavior.

Is there a way I can capture the raw payload as received by Lambda? Any other guidance one debugging?

**Comment by bnusunny** [comment]
You can add `RUST_LOG=debug` as env var to the function. This enables debug loging for LWA. 

Can you share a sample repo with mini code to reproduce this issue?

**Comment by mkdynamic** [comment]
@bnusunny Here is a minimal repro case: https://github.com/mkdynamic/lwa-repro

Note this is using ARM64 not x86.

The container has `RUST_` debug flags set, although the log output isn't that illuminating.

**Comment by bnusunny** [comment]
Thanks for the repro. I deployed it for both arm64 and x86_64. None could reproduce this issue. I'm not sure what could cause your issue...

**Comment by bnusunny** [comment]
Could you remove LWA images from you local computer and rebuild the docker image again? Or try use the Lambda layer with Zip packages?

**Comment by mkdynamic** [comment]
I’ll see if I can clear any locally cached versions of LWA and rebuild. Since the Dockerfile is pointing directly to the ECR public repro which is presumably immutable and hashed I am not optimistic :)

One other details that is maybe relevant, above repro is us-east-1. Seems like a long shot but wonder if there are regional differences in Lambda request handling for function URLs.

Another idea, build the above repro and put it in a public ECR repro. Then can be sure there is nothing about the build that is different between mine and your Lambda function. Rule that out at least. I can share a public build of that image or I am happy to install a public build you share if you prefer. I think this would be a good way to rule out a bunch of possibilities.

**Comment by bnusunny** [comment]
Could you share your image?

**Comment by mkdynamic** [comment]
Here is a fresh ARM64 build of https://github.com/mkdynamic/lwa-repro, using the following build command:

```bash
docker build -t mkdynamic/lwa-repro --platform lunar/arm64 .
```

Here is the image on a brand new public ECR repo:

https://gallery.ecr.aws/i4f8c0j2/mkdynamic/lwa-repro

Because Lambda doesn't support container images from public ECR directly, I made a Dockerfile with:

```Dockerfile
FROM public.ecr.aws/i4f8c0j2/mkdynamic/lwa-repro:latest
```

And built that with:

```bash
docker build --platform linux/amd64 --tag lwa-repro .
```

Then pushed it a brand new private ECR repo:

I then created a Lambda function in us-east-1 with that container image. ARM64 platform, everything else default settings.

A good request:

```bash
$ curl -vvqs "https://XXX.lambda-url.us-east-1.on.aws/?q=a"
...
> GET /?q=a HTTP/1.1
> Host: XXX.lambda-url.us-east-1.on.aws
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 23 Aug 2024 02:31:24 GMT
< Content-Type: text/plain
< Content-Length: 2
< Connection: keep-alive
< x-amzn-RequestId: e053e11c-00bf-45c1-95de-17234022c004
< x-amzn-Remapped-content-length: 2
< x-amzn-Remapped-connection: Keep-Alive
< x-amzn-Remapped-server: WEBrick/1.8.1 (Ruby/3.3.3/2024-06-12)
< content-lenth: 2
< X-Amzn-Trace-Id: root=1-66c7f47a-2cf014a463d27bb21c1ab693;parent=70359ab65a5f28cd;sampled=0;lineage=b2432cb4:0
< x-amzn-Remapped-date: Fri, 23 Aug 2024 02:31:24 GMT
<
* Connection #0 to host XXX.lambda-url.us-east-1.on.aws left intact
hi
```

And the bug:

```bash
$ curl -vvqs "https://XXX.lambda-url.us-east-1.on.aws/?q=a+b"
...
> GET /?q=a+b HTTP/1.1
> Host: XXX.lambda-url.us-east-1.on.aws
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Date: Fri, 23 Aug 2024 02:31:27 GMT
< Content-Type: application/json
< Content-Length: 21
< Connection: keep-alive
< x-amzn-RequestId: 0b7d0e7d-0017-4e3e-831f-04a615c5fa47
< X-Amzn-Trace-Id: root=1-66c7f47f-346c373f76106f1037c6703e;parent=0c2b76080fc27345;sampled=0;lineage=b2432cb4:0
<
* Connection #0 to host XXX.lambda-url.us-east-1.on.aws left intact
Internal Server Error
```

I can repro this 100% of the time with this image and those steps. It will be very confusing if you cannot repro from this image...

When you test, are you using Curl? Wondering if some browsers may recode `+`.

**Comment by mkdynamic** [comment]
Also, here is the complete log output from the above failed request:
https://gist.github.com/mkdynamic/464c4eb162aa4e7ca450274638b34cfb

**Comment by mkdynamic** [comment]
Ah, just found an interesting extra bit of detail – if I call the exact same function above via a brand new HTTP API Gateway, then it works fine with the `+`.

So this seems specific to calling the lambda function URL directly (or as an origin from a CloudFront distribution).

**Comment by mkdynamic** [comment]
@bnusunny Try calling the Function URL directly of the Lambda behind your example in https://httpbin-rest-zip.beta.adapter.awsguru.dev/get?q=a+b

(I don't know the Function URL of that Lambda so I cannot check it).

**Comment by bnusunny** [comment]
I reproduced your issue in a new account. It seems a change is rolling out in us-east-1. I have inform the team about this issue.

**Comment by bnusunny** [comment]
@mkdynamic Could you please open a support ticket with AWS Support and DM me the ticket number?

**Comment by mkdynamic** [comment]
@bnusunny Done – case number is 172446568600460

**Comment by mkdynamic** [comment]
@bnusunny See the response on that ticket?

**Comment by bnusunny** [comment]
Let's continue this conversion on the ticket.
