### ISSUE TITLE
Integrating with X-Ray active tracing

### ISSUE THREAD

**Issue by tmokmss** [awslabs/aws-lambda-web-adapter#85]
Hi! I'm new to this solution and I've come across an issue regarding with X-Ray tracing.

I'm trying to run the below express app:

```ts
import express from 'express';
import http from 'http';
import https from 'https';
import * as AWSXRay from 'aws-xray-sdk-core';
import axios from 'axios';

AWSXRay.captureHTTPsGlobal(http, false);
AWSXRay.captureHTTPsGlobal(https, false);
AWSXRay.capturePromise();

const app = express();

app.get('/', async (_, res) => {
  await axios.get('https://amazon.com');
  res.send('success');
});


const port = 8080;
app.listen(port, () => {
  console.log(`start listening on ${port}`);
});
```

But on every request I get the following error:

```
EXTENSION Name: lambda-adapter State: Ready Events: []
START RequestId: ae5524d6-7d83-4886-8ba1-443b8eea4d48 Version: $LATEST
Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.
at Object.contextMissingLogError [as contextMissing] (/app/server.js:23506:23)
at Segment.resolveLambdaTraceData (/app/server.js:24587:47)
at Object.getSegment (/app/server.js:23550:21)
at Object.resolveSegment (/app/server.js:23537:23)
at captureOutgoingHTTPs (/app/server.js:27474:37)
at Object.captureHTTPsRequest [as request] (/app/server.js:27548:16)
at RedirectableRequest._performRequest (/app/server.js:28819:59)
at new RedirectableRequest (/app/server.js:28663:12)
at Object.request (/app/server.js:28966:18)
at dispatchHttpRequest (/app/server.js:29264:29)
Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.
at Object.contextMissingLogError [as contextMissing] (/app/server.js:23506:23)
at Segment.resolveLambdaTraceData (/app/server.js:24587:47)
at Object.getSegment (/app/server.js:23550:21)
at tryGetCurrentSegment (/app/server.js:27608:29)
at Promise2.then (/app/server.js:27575:49)
at dispatchRequest (/app/server.js:30372:30)
at Axios.request (/app/server.js:30625:19)
at Axios.<computed> [as get] (/app/server.js:30641:21)
at Function.wrap [as get] (/app/server.js:27757:19)
at /app/server.js:30831:30
END RequestId: ae5524d6-7d83-4886-8ba1-443b8eea4d48
```

I confirmed tracing is enabled in CDK as below:

```ts
    const docker = new lambda.DockerImageFunction(this, 'Docker', {
      code: lambda.DockerImageCode.fromImageAsset('./lambda'),
      tracing: lambda.Tracing.ACTIVE,
    });
```

When I run the same app with `serverless-express`, the X-Ray tracing is working fine. I'm assuming it is something related to lambda-web-adapter. [The doc](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-configuration.html#xray-sdk-nodejs-configuration-envvars) says the errors are `related to missing segments or subsegments can occur when you attempt to use an instrumented client in startup code that runs when no request is open, or in code that spawns a new thread.` As they happens even on non-cold-start time, I guess with lambda-web-adapter, express process is spawned as a different process from Lambda main handler, and it results in context missing error.

Is there possibly some workaround? Thanks!

**Comment by bnusunny** [comment]
Yes, lambda web adapter is an extension and running in a separate process. However the adapter fowards the header `x-amzn-trace-id` to the web server. 

X-Ray SDK for node.js should work. 
https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-middleware.html

**Comment by tmokmss** [comment]
Hi @bnusunny, creating X-Ray segment explicitly seems to solve the error. e.g.

```ts
import * as AWSXRay from 'aws-xray-sdk';
import axios from 'axios';

const app = express();

app.use(AWSXRay.express.openSegment('MyApp'));
app.get('/', async (_, res) => {
  await axios.get('https://amazon.com');
  res.send('success');
});
app.use(AWSXRay.express.closeSegment());
``` 

Thanks for the advice!
